from pathlib import Path
from typing import Dict, List, Any, Optional
import re
import logging
from log import log_progress
from importlib.metadata import version

logger = logging.getLogger(__name__)

HEADER_START_LINE = "HEADER;"
HEADER_END_LINE = "FILE_SCHEMA(('AUTOMOTIVE_DESIGN { 1 0 10303 214 1 1 1 1 }'));"
PRODUCT_LINE_CQ = "= PRODUCT("
PRODUCT_LINE_F360 = "=PRODUCT"


def prepare_metadata_string(metadata: Dict[str, str], filename: str, part: Optional["Part"]) -> str:
    return f"""{HEADER_START_LINE}
/* Generated by STEPhen tool v{version('stephen')}
 * by Antmicro (www.antmicro.com) 
 */

FILE_DESCRIPTION(
/* description */ ('{part.description if part else 'Mechanical assembly'}'),
/* implementation_level */ '2;1');

FILE_NAME(
/* name */ '{filename}',
/* time_stamp */ '{metadata.get("time_stamp")}',
/* author */ 'Antmicro',
/* commit_sha */ '{metadata.get("commit_sha")}',
/* commit_msg */ '{metadata.get("commit_msg")}',
/* generator_ver */ '{version('stephen')}');

{HEADER_END_LINE}"""


def prepare_properties_string(part: "Part") -> str:
    return f"{PRODUCT_LINE_CQ}'{part.part_number}','{part.part_name}', '{part.description}',("


def add_metadata(path: Path | str, metadata: Dict[str, str], part: Optional["Part"] = None) -> None:
    with open(path, "r") as step:
        raw_step = step.read()

    metadata_str = prepare_metadata_string(metadata, Path(path).name, part)
    REGEX = rf"{re.escape(HEADER_START_LINE)}?(.*?){re.escape(HEADER_END_LINE)}"

    with open(path, "w") as step:
        step.write(re.sub(REGEX, metadata_str, raw_step, flags=re.DOTALL))


def add_properties(path: Path | str, part: "Part") -> None:
    with open(path, "r") as step:
        raw_step = step.read()

    metadata_str = prepare_properties_string(part)
    REGEX = rf"{re.escape(PRODUCT_LINE_CQ)}[\s\S]*?,\("

    with open(path, "w") as step:
        step.write(re.sub(REGEX, metadata_str, raw_step, flags=re.DOTALL))


def parse_product_data(path: Path) -> Dict[str, List[Any]]:
    REGEX = rf"#[0-9]+{re.escape(PRODUCT_LINE_F360)}\(\s*(.*?)\s*,\s*(.*?)\s*,\s*(.*?)\s*,\s*\(#[0-9]+\)\s*\)"

    with open(path, "r") as step:
        raw_step = step.read().replace("\n", "")

    matches = re.findall(REGEX, raw_step, re.DOTALL)
    matches = [[(item.strip("'\"")) for item in match] for match in matches]
    return {match[1]: match for match in matches}


def parse_metadata(path: Path | str) -> Dict[str, str]:
    with open(path, "r") as step:
        raw_step = step.read()

    keys = ["time_stamp", "commit_sha", "commit_msg", "generator_ver"]
    REGEX = rf".*({ '|'.join(map(re.escape, keys)) }).*'(.*?)'[,)]"
    metadata = dict(re.findall(REGEX, raw_step))

    logger.info(f"Metadata parsed from {path}:")
    for v, k in metadata.items():
        log_progress(f"{v}: {k}")
    return metadata
